### ISSUE TITLE
Your Dockerfile may not be reproducable

### ISSUE THREAD

**Issue by DavidJFelix** [remmelt/docker-gc-image#1]
You're pulling from master on the docker-gc repo and then issuing a shasum of the expected version. Master isn't a stable place to point, so it may not be possible to build the image you intend. You should have the commit hash you're intending to build with in the URL.

https://raw.githubusercontent.com/spotify/docker-gc/master/docker-gc

should be

https://raw.githubusercontent.com/spotify/docker-gc/d7018ed5a422a4586cd46bf368d1d7127de621aa/docker-gc

Reproducibility is essential and an important part of the docker community. Further, there's a bug in docker-gc, so it's hard for me to tell which version you're using since shasum is not a commit hash.

**Comment by DavidJFelix** [comment]
This is also important because https://github.com/spotify/docker-gc/pull/20 may not work with your tagged docker version, depending on version.

**Comment by rohansingh** [comment]
FYI we had some lovely people merge in a Dockerfile to the docker-gc project, so there's now a `spotify/docker-gc` image in the public Docker index.

**Comment by DavidJFelix** [comment]
@rohansingh this is probably the right way to do things going forward, but it's worth noting that this (not reproducible) image has 45,000 downloads on the public Docker index at the time of posting.

**Comment by remmelt** [comment]
Hey, thanks for opening this issue. I appreciate it!

You're totally correct, I should have used the direct link to the commit instead of using master. Fixed that.

I'm going to add a remark in my readme that directs people over to the official docker image.

A remark on the 45K downloads: even though I'll probably brag about it for a while :), these are probably mostly our own systems downloading the image. This is also why I'm leaving the image up for now.

Thanks again!

**Comment by rohansingh** [comment]
@remmelt Great, thanks! Let me know if you have any issues with the spotify/docker-gc image.
